### ISSUE TITLE
Is there a quick start mainly elaborating the NSDI paper - CherryPick?

### ISSUE THREAD

**Issue by xiandong79** [yale-cns/cherrypick#1]
It is a little hard to figure out which part of the code is:

1. how to select initial 3 quasirandom training points
2. the import of Bayesian optimization python lib3
3. the definition of  acquisition function

Is it possible to provide a guidance like  [Ernest-github](https://github.com/amplab/ernest) which is nicely organized and illustrated?

Thanks a lot.

**Comment by iSultan** [comment]
@xiandong79 Were you able to run the code?

**Comment by SiGe** [comment]
@iSultan look into https://github.com/harvard-cns/cherrypick/tree/master/spearmint/examples/cherrypick

You should pass Cherrypick as the example to execute to spearmint.

**Comment by iSultan** [comment]
@SiGe I actually did 
`python2.7 spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 ../spearmint/examples/cherrypick/cherrypick.pb`

and this is what I got

    Current best: No results returned yet.
    19975 candidates   0 pending   0 complete   0 executed
    Choosing next candidate... 
    Expected improvement: 1000.000000
    >>>>>>> 0 1000
    selected job 25 from the grid.
    Submitted job as process: 34683
    submitted - pid = 34683

**Comment by SiGe** [comment]
It seems like there is a lot going on with the Spearmint dependencies.   I'll have to freeze the pip recipes we used during the submission.  Is your work critical?  If not, I will take a look into this next week.

**Comment by iSultan** [comment]
It turns out that I had to install `sqlobject`. However, I still can't run the code. The current error is: 

    Traceback (most recent call last):
       File "spearmint/main.py", line 373, in <module>
        main()
      File "spearmint/main.py", line 187, in main
        while attempt_dispatch(experiment_config, expt_dir, chooser, driver, options):
      File "spearmint/main.py", line 300, in attempt_dispatch
        params = job_params(job)
      File "/cherrypick-master/spearmint/spearmint/runner.py", line 108, in job_params
        dbl_vals = param.dbl_val._values
    AttributeError: 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values'

We are at the stage where we compare our work with different baselines.

**Comment by SiGe** [comment]
Yes, that's the error that I get, too.  Maybe try installing older versions of protobuf and see if that fixes it?

**Comment by iSultan** [comment]
I tried `protobuf-2.6.1` and `protobuf-3.1.0` and I got the same error. 
Btw, the `braninpy` example works with me.

**Comment by jatinarora2409** [comment]
@xiandong79  Were you able to figure out 'how to select initial 3 quasirandom training points' ?
